filomenas/urls.py
from django.urls import path
from . import views

app_name = "filomenas"

urlpatterns = [
    # nao logado
    path('', views.Home.as_view(), name='home'),
    path('filo/', views.filomena_nao.as_view(), name="filomena_nao"),

    # logado
    path('home2/', views.Home2.as_view(), name='home2'),    
    path('perfil/', views.Perfil.as_view(), name="perfil"),
    
    #listar
    path('listar/', views.ListarEstadia.as_view(), name="listar_log"),
    path('listarfilo/', views.ListarEstadiafilo.as_view(), name="listar_filo"),
    path('listarfilomena/', views.Listarfilomena.as_view(), name="listar_filomena"),
    path('listar_nao/', views.ListarEstadianao.as_view(), name="listar_nao"),

    #detalhar
    path('detalhar_log/<int:pk>/', views.Detalharestadialog.as_view(), name="detalhar_log"),
    path('detalhar/<int:pk>/', views.DetalharEstadia.as_view(), name="detalhar"),

    #criar
    path('criar/', views.CriarEstadia.as_view(), name="criar"),
    path('criar_hospede/', views.Criarhospede.as_view(), name="criar_hospede"),
    path('criar_filomena/', views.Criarfilomena.as_view(), name="criar_filomena"),
    path('forms/', views.forms.as_view(), name="forms"),
 
    #apagar
    path('apagar_filomena/<int:pk>/', views.Apagarfilomena.as_view(), name='apagar_filomena'),
    path('apagar_estadia/<int:pk>/', views.ApagarEstadia.as_view(), name='apagar_estadia'),

    #atualizar
    path('atualizar_estadia/<int:pk>/', views.AtualizarEstadia.as_view(), name="atualizar_estadia"),
    path('atualizar_filomena/<int:pk>/', views.Atualizarfilomena.as_view(), name="atualizar_filomena"),

    path('atualizar_hosp/<int:pk>/', views.Atualizarhospede.as_view(), name="atuar_hospede"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path("", include("filomenas.urls", namespace="filomenas")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filomenas/models.py
from django.db import models
from operator import mod
from django.db import models

class Produtos(models.Model):
    nome = models.CharField(max_length=120)
    preco = models.FloatField()
    imagem = models.ImageField()
    descricao_produto = models.CharField(max_length=1000)

class hospede(models.Model):
    nome = models.CharField(max_length=120)
    profissao = models.CharField(max_length=120)
    email = models.EmailField(null=True)
    idade = models.IntegerField()
    imagem_perfil = models.ImageField(null=True)
    telefone = models.CharField(max_length=20, null=True)
    formulario_enviado = models.BooleanField(default=False)

class filomenas(models.Model):
    nome = models.CharField(max_length=120)
    idade = models.IntegerField()
    descricao = models.CharField(max_length=1000)
    imagem_filo = models.ImageField(null=True)
    email = models.EmailField(null=True)
    telefone = models.CharField(max_length=20, null=True)

class estadia(models.Model):
    imagem = models.ImageField(null=True)
    duracao = models.IntegerField()
    nome_estadia = models.CharField(max_length=200)
    descricao_estadia = models.CharField(max_length=1000)
    localizacao = models.CharField(max_length=500)
    valor = models.DecimalField(verbose_name=("valor"), decimal_places=2, max_digits=6)    
    programacao = models.CharField(max_length=1000, null=True)

filomenas/forms.py
from django import forms
from .models import Produtos, hospede, filomenas, estadia

class ProdutosForm(forms.ModelForm):
    class Meta:
        model = Produtos
        fields = ['nome', 'preco', 'imagem', 'descricao_produto']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Produto'}),
            'preco': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Preço'}),
            'imagem': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'descricao_produto': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descrição do Produto'}),
        }

class HospedeForm(forms.ModelForm):
    class Meta:
        model = hospede
        fields = ['nome', 'profissao', 'email', 'idade', 'imagem_perfil', 'telefone']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Hóspede'}),
            'profissao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Profissão'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'idade': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Idade'}),
            'imagem_perfil': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone'}),
        }

class FilomenasForm(forms.ModelForm):
    class Meta:
        model = filomenas
        fields = ['nome', 'idade', 'imagem_filo', 'email', 'telefone']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}),
            'idade': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Idade'}),
            'imagem_filo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone'}),
        }

class EstadiaForm(forms.ModelForm):
    class Meta:
        model = estadia
        fields = ['imagem', 'duracao', 'nome_estadia', 'descricao_estadia', 'localizacao', 'valor', 'programacao']
        widgets = {
            'imagem': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'duracao': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Duração'}),
            'nome_estadia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome da Estadia'}),
            'descricao_estadia': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descrição da Estadia'}),
            'localizacao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Localização'}),
            'valor': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Valor'}),
            'programacao': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Programação'}),
        }

filomenas/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.views import generic
from django.views.generic import ListView,CreateView,DeleteView,DetailView, UpdateView,TemplateView
from django.urls import reverse_lazy
from django_filters.views import FilterView
from .filter import EstadiaFilter
from django.contrib.messages import views
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import EstadiaForm, ProdutosForm, HospedeForm, FilomenasForm
from .models import estadia, Produtos, filomenas, hospede
from users.permissions import AdminPermission


# não logado

class Home(generic.TemplateView):
    template_name = "nao/home.html"
    
class filomena_nao(generic.TemplateView):
    template_name = "nao/filomena.html"

# logado

class Home2(generic.TemplateView):
    template_name = "logado/home2.html"

class forms(generic.TemplateView):
    template_name = "logado/forms.html"
    

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>....
#                                                                        CRUDS

# CRUD de Estadia
class ListarEstadia(LoginRequiredMixin, generic.ListView, FilterView):
    model = estadia
    template_name = 'estadia/listar.html'
    context_object_name = 'estadias'
    filterset_class = EstadiaFilter
    paginate_by = 3

class ListarEstadiafilo(LoginRequiredMixin, generic.ListView, FilterView):
    model = estadia
    template_name = 'filomenas/listar_estadia.html'
    context_object_name = 'estadias'
    filterset_class = EstadiaFilter
    paginate_by = 3
    
class ListarEstadianao( generic.ListView):
    model = estadia
    template_name = 'estadia/listar_nao.html'
    context_object_name = 'estadias'
    paginate_by = 3

class Detalharestadialog(generic.DetailView):
    model = estadia
    template_name = 'estadia/detalhar_logado.html'

class DetalharEstadia(generic.DetailView):
    model = estadia
    template_name = 'estadia/detalhar.html'


class CriarEstadia(LoginRequiredMixin, views.SuccessMessageMixin, generic.CreateView):
    model = estadia
    form_class = EstadiaForm
    template_name = 'estadia/form.html'
    success_url = reverse_lazy("filomenas:listar_log")
    success_message = "Estadia cadastrada com sucesso!"

class AtualizarEstadia(AdminPermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = estadia
    form_class = EstadiaForm
    template_name = "estadia/form.html"
    success_url = reverse_lazy("filomenas:listar_filo")
    success_message = "Estadia atualizada com sucesso!"
    
class Atualizarfilomena(AdminPermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = filomenas
    form_class = FilomenasForm
    template_name = 'filomenas/form.html'
    success_url = reverse_lazy("filomenas:listar_filomena")
    success_message = "Perfil atualizado com sucesso, {{ request.user.username }}!" 


class ApagarEstadia(AdminPermission, LoginRequiredMixin, generic.DeleteView):
    model = estadia
    success_url = reverse_lazy("filomenas:listar_filo")
    success_message = "Estadia removida com sucesso!"

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>....
    
# CRUD de perfil do hospede 

class Perfil(LoginRequiredMixin,generic.TemplateView):
    model = hospede
    template_name = 'logado/perfil.html'
    
class Listarhospede(LoginRequiredMixin, generic.ListView):
    model = hospede
    template_name = 'logado/perfilinfo.html'
    context_object_name = 'hospedes'

class Detalharhospede(generic.DetailView):
    model = hospede
    template_name = "perfil/form_hospede.html"

class Criarhospede(LoginRequiredMixin, views.SuccessMessageMixin, generic.CreateView):
    model = hospede
    form_class = HospedeForm
    template_name = 'perfil/form_hospede.html'
    success_url = reverse_lazy("filomenas:perfil")
    success_message = "Hospede cadastrado com sucesso!"
       

class Atualizarhospede(LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = hospede
    form_class = HospedeForm
    template_name = "perfil/form_hospede.html"
    success_url = reverse_lazy("filomenas:listar_hospede")
    success_message = "Perfil atualizado com sucesso"

class Apagarhospede(AdminPermission, LoginRequiredMixin, generic.DeleteView):
    model = hospede
    success_url = reverse_lazy("filomenas:home")
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>....
  
# CRUD de perfil filomenas

class Detalharfilomena(generic.DetailView):
    model = filomenas
    template_name = 'filomenas/detalhar_filo.html'

class Listarfilomena(LoginRequiredMixin, generic.ListView):
    model = filomenas
    template_name = 'filomenas/listar_filomenas.html'
    context_object_name = 'filomenas'
    paginate_by = 3

class Criarfilomena(views.SuccessMessageMixin, generic.CreateView):
    model = filomenas
    form_class = FilomenasForm
    template_name = 'filomenas/form.html'
    success_url = reverse_lazy("filomenas:listar_filomena")
    success_message = "filomena cadastrada com sucesso!"

class CriarEstadia(LoginRequiredMixin, views.SuccessMessageMixin, generic.CreateView):
    model = estadia
    form_class = EstadiaForm
    template_name = 'estadia/form.html'
    success_url = reverse_lazy("filomenas:listar_filo")
    success_message = "Estadia cadastrada com sucesso!"

class Atualizarfilomena(AdminPermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = filomenas
    form_class = FilomenasForm
    template_name = 'filomenas/form.html'
    success_url = reverse_lazy("filomenas:listar_filomena")
    success_message = "Perfil atualizado com sucesso, {{ request.user.username }}!" 

class Apagarfilomena(AdminPermission, LoginRequiredMixin, generic.DeleteView):
    success_message = "Filomena removida com sucesso!"
    model = filomenas
    success_url = reverse_lazy("filomenas:listar_filomena")

filomenas/templates/estadia/apagar.html
{% extends 'base_logada.html' %}
{% load static %}
<!-- 

<form action="{% url 'filomenas:apagar_estadia' estadia.pk %}" method="post">
    {% csrf_token %}
    <div class="modal fade" id="exampleModal-{{ object.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmação de Exclusão</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Deseja excluir o registro {{ object }}?
            {{ object.pk }}
            {{ form }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Excluir</button>
        </div>
      </div>
    </div>
  </div>
</form>
 -->


{% block body %}
<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

<br><br>

<h3 class="m-3 text-center">Excluir Estadia</h3>

<div class="m-3 text-center">

    <form method="post">
        <section class="form container-fluid p-5x ">
            {% csrf_token %}

                <p> Você tem certeza que quer apagar esta estadia?</p>
                {{ form }}
        </section>
        
            </div>

    </form>
    <br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br>

{% endblock %}

filomenas/templates/estadia/detalhar.html
{% extends 'base_nao.html' %}
{% load static %}


{% block title %}
Detalhe_estadia
{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

<style>

    .product-container {
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 10px;
    }

    .product-image {
        border-radius: 10px 0 0 10px;
    }

    .product-info {
        padding: 20px;
    }
    .text-orange{
        color: #E28743;
    }
    .text-orangee{
background-color: #E28743;
    }
    .product-price {
        font-size: 1.5rem;
        color: #E28743; /* verde */
    }

    .product-description {
        margin-top: 20px;
    }

    .btn-buy, .btn-back {
        width: 100%;
        margin-top: 20px;
    }
</style> 
<div class="m-4">
    <div class="container product-container">
        <h2 class="p-3 mb-1 mt-2 text-orange">Estadia: {{ estadia.nome_estadia }}</h2>
        <hr>
        <div class="row">
            <div class="col-md-6 product-image">
                <img src="{{ estadia.imagem.url }}" alt="Imagem" class="img-fluid rounded-top">
            </div>
            <div class="col-md-6 product-info">
                <p class="product-price"><strong>Valor:</strong> R$ {{ estadia.valor }}</p>
                <p class="duracao"><strong>Duração:</strong> {{ estadia.duracao }} dias</p>
                <p class="product-description"><strong>Descrição:</strong> {{ estadia.descricao_estadia }}</p>
                <p class="localizacao"><strong>Localização:</strong> {{ estadia.localizacao }}</p>
                <p class="programacao"><strong>Programação:</strong> {{ estadia.programacao }}</p>
                <hr>
                 <a href="{% url 'account_login' %}" class="btn text-orangee btn-buy">Reservar</a>
                <a href="{% url 'filomenas:listar_nao' %}" class="btn btn-secondary btn-back">Voltar</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

filomenas/templates/estadia/detalhar_logado.html
{% extends 'base_logada.html' %}
{% load static %}


{% block title %}
Detalhe_estadia
{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

<style>
    .product-container {
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 10px;
    }

    .product-image {
        border-radius: 10px 0 0 10px;
    }

    .product-info {
        padding: 20px;
    }
    .text-orange{
        color: #E28743;
    }
    .text-orangee{
    background-color: #E28743;
    }
    .product-price {
        font-size: 1.5rem;
        color: #E28743; /* verde */
    }

    .product-description {
        margin-top: 20px;
    }

    .btn-buy, .btn-back {
        width: 100%;
        margin-top: 20px;
    }
</style> 
<div class="m-4">
    <div class="container product-container">
        <h2 class="p-3 mb-5  text-orange">Estadia: {{ estadia.nome_estadia }}</h2>
        <hr>
        <div class="row">
            <div class="col-md-6 product-image">
                <img src="{{ estadia.imagem.url }}" alt="Imagem" class="img-fluid rounded-top">
            </div>
            <div class="col-md-6 product-info">
                <p class="product-price"><strong>Valor:</strong> R$ {{ estadia.valor }}</p>
                <p class="duracao"><strong>Duração:</strong> {{ estadia.duracao }} dias</p>
                <p class="product-description"><strong>Descrição:</strong> {{ estadia.descricao_estadia }} <br></p>
                <p class="localizacao"><strong>Localização:</strong> {{ estadia.localizacao }}</p>
                <p class="programacao"><strong>Programação:</strong> {{ estadia.programacao }}</p>
                <hr>
                <a href="#" class="btn text-orangee btn-buy">Reservar</a>
                <a href="{% url 'filomenas:listar_log' %}" class="btn btn-secondary btn-back">Voltar</a>
            </div>
        </div>
    </div>
</div>





{% endblock %}

filomenas/templates/estadia/listar.html
{% extends 'base_logada.html' %}
{% load i18n %}
{% load static %}

{% block body %}
<style>
    .text-orange {
        background-color: #E28743; /* Laranja queimado */
        transition: color 0.3s ease; /* Adicionando uma transição suave para a mudança de cor */
        font-size: 16px;
    }

    .text-orange:hover {
        background-color: #FF8C00; /* Mudança de cor ao passar o mouse por cima */
    }
    .text-orangee{
        color: #E28743;
    }
</style>

<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 30px;" />

<form method="GET" action="{% url 'filomenas:listar_log' %}" autocomplete="off">
    <!-- <section class="form container-fluid p-5x">
       Seu formulário de filtro aqui 
    </section> -->
</form>

<div class="container text-center">
    <div class="row row-cols-2 mt-3">
        {% for estadia in estadias %}
            <div class="col-md-4">
                <div class="m-5">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ estadia.imagem.url }}" alt="Imagem da Estadia" >
                        <div class="card-body">
                            <h5 class="card-title text-orangee">Nome da Estadia: <strong>{{ estadia.nome_estadia }}</strong></h5>
                            <p class="card-text">Descrição: {{ estadia.descricao_estadia }}</p>
                            <a href="{% url 'filomenas:detalhar_log' pk=estadia.pk %}" class="btn text-orange">Reservar</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">
                <p class="text-h1">Não existem estadias cadastradas.</p>
            </div>
        {% endfor %}
    </div>
</div>


<style>
  .pagination-container {
      margin-top: 20px;
  }

  .pagination {
      display: flex;
      justify-content: center;
      list-style: none;
  }

  .page-item {
      margin: 0 5px;
  }

  .page-link {
      color: #E28743;
      background-color: #fff;
      border: 1px solid #E28743;
  }

  .page-link:hover,
  .page-link:focus {
      color: #fff;
      background-color: #E28743;
      border: 1px solid #E28743;
  }

  .page-item.active .page-link {
      z-index: 3;
      color: #fff;
      background-color: #E28743;
      border: 1px solid #E28743;
  }
</style>



<div class="container text-center">
  <div class="row">
      <div class="col"></div>
      <div class="col">
          <div class="pagination-container">
              <ul class="pagination">
                  {% if page_obj.has_previous %}
                      <li class="page-item">
                          <a class="page-link" href="?page=1&search={{ request.GET.search }}" aria-label="First">
                              <span aria-hidden="true">&laquo;&laquo;</span>
                          </a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}" aria-label="Previous">
                              <span aria-hidden="true">&laquo;</span>
                          </a>
                      </li>
                  {% endif %}

                  {% for pg in page_obj.paginator.page_range %}
                      <li class="page-item {% if page_obj.number == pg %}active{% endif %}">
                          <a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a>
                      </li>
                  {% endfor %}

                  {% if page_obj.has_next %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                          </a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}" aria-label="Last">
                              <span aria-hidden="true">&raquo;&raquo;</span>
                          </a>
                      </li>
                  {% endif %}
              </ul>
          </div>
      </div>
      <div class="col"></div>
  </div>
</div>
<br><br><br><br><br><br>

{% endblock body %}

filomenas/templates/estadia/listar_nao.html
{% extends 'base_nao.html' %}
{% load static %}



{% block body %}
<style>
  .text-orange {
      background-color: #E28743; /* Laranja queimado */
      transition: color 0.3s ease; /* Adicionando uma transição suave para a mudança de cor */
      font-size: 16px;
  }

  .text-orange:hover {
      background-color: #FF8C00; /* Mudança de cor ao passar o mouse por cima */
  }
  .text-orangee{
      color: #E28743;
  }
</style>
    
  <!-- {% if messages %}
    {% for message in messages %}
      <div{% if message.tags %} class="{{ message.tags }} p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3 m-4 text-center"{% endif %}>
        {{ message }}
      </div>
    {% endfor %}
  {% endif %} -->
  <img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

  <div class="container text-center">
    <div class="row row-cols-2 mt-3">
      {% for estadia in estadias %}
        <div class="col-md-4">
          <div class="m-5">
            <div class="card" style="width: 18rem;">
              <img src="{{ estadia.imagem.url }}" alt="Imagem da Estadia" >
              <div class="card-body">
                <h5 class="card-title text-orangee">Nome da Estadia: <strong>{{ estadia.nome_estadia }}</strong></h5>
                <p class="card-text">Descrição: {{ estadia.descricao_estadia }}</p>
                <a href="{% url 'filomenas:detalhar' pk=estadia.pk %}" class="btn text-orange">Reservar/a>

              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <div class="col-md-12">
          <p class="text-h1">Não existem estadias cadastradas.</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="container text-center">
    <div class="row">
      <div class="col"></div>
      <div class="col">
        <div class="w3-bar">
          <!-- Código de paginação -->
          <!-- ... -->
        </div>
      </div>
      <div class="col"></div>
    </div>
  </div>

  <style>
    .pagination-container {
        margin-top: 20px;
    }

    .pagination {
        display: flex;
        justify-content: center;
        list-style: none;
    }

    .page-item {
        margin: 0 5px;
    }

    .page-link {
        color: #E28743;
        background-color: #fff;
        border: 1px solid #E28743;
    }

    .page-link:hover,
    .page-link:focus {
        color: #fff;
        background-color: #E28743;
        border: 1px solid #E28743;
    }

    .page-item.active .page-link {
        z-index: 3;
        color: #fff;
        background-color: #E28743;
        border: 1px solid #E28743;
    }
</style>



  <div class="container text-center">
    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="pagination-container">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1&search={{ request.GET.search }}" aria-label="First">
                                <span aria-hidden="true">&laquo;&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for pg in page_obj.paginator.page_range %}
                        <li class="page-item {% if page_obj.number == pg %}active{% endif %}">
                            <a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a>
                        </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}" aria-label="Last">
                                <span aria-hidden="true">&raquo;&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>


{% endblock body %}
    