filomenas/urls.py
from django.urls import path
from . import views

app_name = "filomenas"

urlpatterns = [
    # nao logado
    path('', views.Home.as_view(), name='home'),
    path('filo/', views.filomena_nao.as_view(), name="filomena_nao"),

    # logado
    path('home2/', views.Home2.as_view(), name='home2'),    
    path('perfil/', views.Perfil.as_view(), name="perfil"),
    
    #listar
    path('listar/', views.ListarEstadia.as_view(), name="listar_log"),
    path('listarfilo/', views.ListarEstadiafilo.as_view(), name="listar_filo"),
    path('listarfilomena/', views.Listarfilomena.as_view(), name="listar_filomena"),
    path('listar_nao/', views.ListarEstadianao.as_view(), name="listar_nao"),

    #detalhar
    path('detalhar_log/<int:pk>/', views.Detalharestadialog.as_view(), name="detalhar_log"),
    path('detalhar/<int:pk>/', views.DetalharEstadia.as_view(), name="detalhar"),

    #criar
    path('criar/', views.CriarEstadia.as_view(), name="criar"),
    path('criar_hospede/', views.Criarhospede.as_view(), name="criar_hospede"),
    path('criar_filomena/', views.Criarfilomena.as_view(), name="criar_filomena"),
    path('forms/', views.forms.as_view(), name="forms"),
 
    #apagar
    path('apagar_filomena/<int:pk>/', views.Apagarfilomena.as_view(), name='apagar_filomena'),
    path('apagar_estadia/<int:pk>/', views.ApagarEstadia.as_view(), name='apagar_estadia'),

    #atualizar
    path('atualizar_estadia/<int:pk>/', views.AtualizarEstadia.as_view(), name="atualizar_estadia"),
    path('atualizar_filomena/<int:pk>/', views.Atualizarfilomena.as_view(), name="atualizar_filomena"),

    path('atualizar_hosp/<int:pk>/', views.Atualizarhospede.as_view(), name="atuar_hospede"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path("", include("filomenas.urls", namespace="filomenas")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filomenas/models.py
from django.db import models
from operator import mod
from django.db import models

class Produtos(models.Model):
    nome = models.CharField(max_length=120)
    preco = models.FloatField()
    imagem = models.ImageField()
    descricao_produto = models.CharField(max_length=1000)

class hospede(models.Model):
    nome = models.CharField(max_length=120)
    profissao = models.CharField(max_length=120)
    email = models.EmailField(null=True)
    idade = models.IntegerField()
    imagem_perfil = models.ImageField(null=True)
    telefone = models.CharField(max_length=20, null=True)
    formulario_enviado = models.BooleanField(default=False)

class filomenas(models.Model):
    nome = models.CharField(max_length=120)
    idade = models.IntegerField()
    descricao = models.CharField(max_length=1000)
    imagem_filo = models.ImageField(null=True)
    email = models.EmailField(null=True)
    telefone = models.CharField(max_length=20, null=True)

class estadia(models.Model):
    imagem = models.ImageField(null=True)
    duracao = models.IntegerField()
    nome_estadia = models.CharField(max_length=200)
    descricao_estadia = models.CharField(max_length=1000)
    localizacao = models.CharField(max_length=500)
    valor = models.DecimalField(verbose_name=("valor"), decimal_places=2, max_digits=6)    
    programacao = models.CharField(max_length=1000, null=True)

filomenas/forms.py
from django import forms
from .models import Produtos, hospede, filomenas, estadia

class ProdutosForm(forms.ModelForm):
    class Meta:
        model = Produtos
        fields = ['nome', 'preco', 'imagem', 'descricao_produto']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Produto'}),
            'preco': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Preço'}),
            'imagem': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'descricao_produto': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descrição do Produto'}),
        }

class HospedeForm(forms.ModelForm):
    class Meta:
        model = hospede
        fields = ['nome', 'profissao', 'email', 'idade', 'imagem_perfil', 'telefone']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Hóspede'}),
            'profissao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Profissão'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'idade': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Idade'}),
            'imagem_perfil': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone'}),
        }

class FilomenasForm(forms.ModelForm):
    class Meta:
        model = filomenas
        fields = ['nome', 'idade', 'imagem_filo', 'email', 'telefone']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}),
            'idade': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Idade'}),
            'imagem_filo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone'}),
        }

class EstadiaForm(forms.ModelForm):
    class Meta:
        model = estadia
        fields = ['imagem', 'duracao', 'nome_estadia', 'descricao_estadia', 'localizacao', 'valor', 'programacao']
        widgets = {
            'imagem': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'duracao': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Duração'}),
            'nome_estadia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome da Estadia'}),
            'descricao_estadia': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descrição da Estadia'}),
            'localizacao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Localização'}),
            'valor': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Valor'}),
            'programacao': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Programação'}),
        }

filomenas/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.views import generic
from django.views.generic import ListView,CreateView,DeleteView,DetailView, UpdateView,TemplateView
from django.urls import reverse_lazy
from django_filters.views import FilterView
from .filter import EstadiaFilter
from django.contrib.messages import views
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import EstadiaForm, ProdutosForm, HospedeForm, FilomenasForm
from .models import estadia, Produtos, filomenas, hospede
from users.permissions import AdminPermission


# não logado

class Home(generic.TemplateView):
    template_name = "nao/home.html"
    
class filomena_nao(generic.TemplateView):
    template_name = "nao/filomena.html"

# logado

class Home2(generic.TemplateView):
    template_name = "logado/home2.html"

class forms(generic.TemplateView):
    template_name = "logado/forms.html"
    

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>....
#                                                                        CRUDS

# CRUD de Estadia
class ListarEstadia(LoginRequiredMixin, generic.ListView, FilterView):
    model = estadia
    template_name = 'estadia/listar.html'
    context_object_name = 'estadias'
    filterset_class = EstadiaFilter
    paginate_by = 3

class ListarEstadiafilo(LoginRequiredMixin, generic.ListView, FilterView):
    model = estadia
    template_name = 'filomenas/listar_estadia.html'
    context_object_name = 'estadias'
    filterset_class = EstadiaFilter
    paginate_by = 3
    
class ListarEstadianao( generic.ListView):
    model = estadia
    template_name = 'estadia/listar_nao.html'
    context_object_name = 'estadias'
    paginate_by = 3

class Detalharestadialog(generic.DetailView):
    model = estadia
    template_name = 'estadia/detalhar_logado.html'

class DetalharEstadia(generic.DetailView):
    model = estadia
    template_name = 'estadia/detalhar.html'


class CriarEstadia(LoginRequiredMixin, views.SuccessMessageMixin, generic.CreateView):
    model = estadia
    form_class = EstadiaForm
    template_name = 'estadia/form.html'
    success_url = reverse_lazy("filomenas:listar_log")
    success_message = "Estadia cadastrada com sucesso!"

class AtualizarEstadia(AdminPermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = estadia
    form_class = EstadiaForm
    template_name = "estadia/form.html"
    success_url = reverse_lazy("filomenas:listar_filo")
    success_message = "Estadia atualizada com sucesso!"
    
class Atualizarfilomena(AdminPermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = filomenas
    form_class = FilomenasForm
    template_name = 'filomenas/form.html'
    success_url = reverse_lazy("filomenas:listar_filomena")
    success_message = "Perfil atualizado com sucesso, {{ request.user.username }}!" 


class ApagarEstadia(AdminPermission, LoginRequiredMixin, generic.DeleteView):
    model = estadia
    success_url = reverse_lazy("filomenas:listar_filo")
    success_message = "Estadia removida com sucesso!"

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>....
    
# CRUD de perfil do hospede 

class Perfil(LoginRequiredMixin,generic.TemplateView):
    model = hospede
    template_name = 'logado/perfil.html'
    
class Listarhospede(LoginRequiredMixin, generic.ListView):
    model = hospede
    template_name = 'logado/perfilinfo.html'
    context_object_name = 'hospedes'

class Detalharhospede(generic.DetailView):
    model = hospede
    template_name = "perfil/form_hospede.html"

class Criarhospede(LoginRequiredMixin, views.SuccessMessageMixin, generic.CreateView):
    model = hospede
    form_class = HospedeForm
    template_name = 'perfil/form_hospede.html'
    success_url = reverse_lazy("filomenas:perfil")
    success_message = "Hospede cadastrado com sucesso!"
       

class Atualizarhospede(LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = hospede
    form_class = HospedeForm
    template_name = "perfil/form_hospede.html"
    success_url = reverse_lazy("filomenas:listar_hospede")
    success_message = "Perfil atualizado com sucesso"

class Apagarhospede(AdminPermission, LoginRequiredMixin, generic.DeleteView):
    model = hospede
    success_url = reverse_lazy("filomenas:home")
  
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>....
  
# CRUD de perfil filomenas

class Detalharfilomena(generic.DetailView):
    model = filomenas
    template_name = 'filomenas/detalhar_filo.html'

class Listarfilomena(LoginRequiredMixin, generic.ListView):
    model = filomenas
    template_name = 'filomenas/listar_filomenas.html'
    context_object_name = 'filomenas'
    paginate_by = 3

class Criarfilomena(views.SuccessMessageMixin, generic.CreateView):
    model = filomenas
    form_class = FilomenasForm
    template_name = 'filomenas/form.html'
    success_url = reverse_lazy("filomenas:listar_filomena")
    success_message = "filomena cadastrada com sucesso!"

class CriarEstadia(LoginRequiredMixin, views.SuccessMessageMixin, generic.CreateView):
    model = estadia
    form_class = EstadiaForm
    template_name = 'estadia/form.html'
    success_url = reverse_lazy("filomenas:listar_filo")
    success_message = "Estadia cadastrada com sucesso!"

class Atualizarfilomena(AdminPermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = filomenas
    form_class = FilomenasForm
    template_name = 'filomenas/form.html'
    success_url = reverse_lazy("filomenas:listar_filomena")
    success_message = "Perfil atualizado com sucesso, {{ request.user.username }}!" 

class Apagarfilomena(AdminPermission, LoginRequiredMixin, generic.DeleteView):
    success_message = "Filomena removida com sucesso!"
    model = filomenas
    success_url = reverse_lazy("filomenas:listar_filomena")

filomenas/templates/logado/filomena.html
{% extends 'base_logada.html' %}
{% load static %}

{% block body %}

<style>
    .product-container {
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 10px;
        margin-top: 20px;
    }

    .product-image {
        border-radius: 10px 0 0 10px;
    }

    .product-info {
        padding: 20px;
    }

    .text-orange {
        color: #E28743;
    }

    .text-orangee {
        background-color: #E28743;
        color: white;
    }

    .product-price {
        font-size: 1.5rem;
        color: #E28743; /* laranja */
    }

    .product-description {
        margin-top: 20px;
    }

    .btn-buy, .btn-back {
        width: 100%;
        margin-top: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 15px;
        text-align: center; /* Ajuste para centralizar o texto */
    }

    th {
        background-color: #E28743; /* laranja */
        color: white;
    }
</style>

<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

<div class="container mt-5">
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead class="text-orange">
                <tr>
                    <th scope="col">Imagem</th>
                    <th scope="col">Nome da Filomena</th>
                    <th scope="col">Idade</th>
                    <th scope="col">Email</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for filomena in filomenas %}
                    <tr>
                        <td>
                            {% if filomena.imagem_filo %}
                                <img src="{{ filomena.imagem_filo.url }}" alt="Imagem da Estadia" width="150px" height="100px">
                            {% else %}
                                Sem imagem
                            {% endif %}
                        </td>
                        <td>{{ filomena.nome }}</td>
                        <td>{{ filomena.email }}</td>
                        <td>{{ filomena.idade }}</td>
                        <td>{{ filomena.telefone }}</td>
                        <td>
                            <a class="btn btn-warning" href="{% url 'filomenas:atualizar_filomena' filomena.pk %}" title="Editar">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                                </svg>
                            </a>
                            <a href="{% url 'filomenas:apagar_filomena' filomena.pk %}" class="btn btn-danger">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                                </svg>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">
                            <p>Não existem Filomenas cadastradas.</p>
                        </td>
                    </tr>
                {% endfor %}


            </tbody>
        </table>
    </div>

    <nav class="br-pagination mt-3" aria-label="Paginação de resultados">
        <!-- Adicione a lógica de paginação aqui se necessário -->
    </nav>
    <div class="row justify-content-between mt-6">
        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
            <a class="btn btn-secondary btn-block" href="#" role="button">
                <i class="fas fa-chevron-left mr-2"></i>Voltar
            </a>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-6 col-12 mt-2 mt-sm-0">
            <a href="{% url 'filomenas:criar_filomena'%}" class="btn text-orangee btn-block" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg> Cadastrar Filomena
            </a>
        </div>
    </div>
</div>

{% endblock %}

filomenas/templates/logado/form_filomena.html
{% extends 'base_logada.html' %}
{% load static %}


{% block body %}
<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

{% endblock%}
    

filomenas/templates/logado/forms.html
{% extends 'base_logada.html' %}
{% load static %}



{% block body %}
<style>
    .text-orange {
        color: #FFA07A; /* Laranja queimado */
        transition: color 0.3s ease; /* Adicionando uma transição suave para a mudança de cor */
        font-size: 16px;
    }

    .text-orange:hover {
        color: #FF8C00; /* Mudança de cor ao passar o mouse por cima */
    }
</style>
<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

<div class="container mt-5">
    <ul class="list-group text-center">
        <li class="list-group-item"><a class="text-decoration-none text-orange" href="{% url 'filomenas:criar' %}">Estadia</a></li>
        <li class="list-group-item"><a class="text-decoration-none text-orange" href="{% url 'filomenas:criar_filomena' %}">Filomenas</a></li>
    </ul>
</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock body %}

filomenas/templates/logado/perfil.html
{% extends 'base_logada.html' %}
{% load static %}

{% block body %}
<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />

<style>
    .text-orangee {
        background-color: #E28743;
    }
    .text-orangee:hover{
        background-color: #f5a76b;
    }
    .b {
        background-color: hsl(26, 73%, 57%);
        color: white;
        padding: 15px 20px;
        border-radius: 10px;
        cursor: pointer;
        display: inline-block;
        transition: 0.1s;
    }

    .b:hover {
        background-color: #f5a76b; /* Mudança de cor ao passar o mouse por cima */
    }

    .container {
        padding-top: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #E28743; /* Cor de fundo para cabeçalho da tabela */
        color: white;
    }
</style>

<div class="container">
    <a href="{% url 'filomenas:criar_hospede' %}" class="btn b">{{ request.user.username }}, finalize suas informações</a>
</div>

<div class="m-4">
    <div class="container product-container">
        <table>
            <thead>
                <tr>
                    <th>Nome completo</th>
                    <th>Profissão</th>
                    <th>Email</th>
                    <th>Idade</th>
                    <th>Telefone</th>
                    <th>Imagem</th>
                </tr>
            </thead>
            <tbody>
                {% for hospede in hospedes %}
                    <tr>
                        <td>{{ hospede.nome }}</td>
                        <td>{{ hospede.profissao }}</td>
                        <td>{{ hospede.email }}</td>
                        <td>{{ hospede.idade }}</td>
                        <td>{{ hospede.telefone }}</td>
                        <td><img src="{{ hospede.imagem_perfil.url }}" alt="Imagem da Estadia" width="150px" height="100px"></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <br><br><br>
        <div class="text-center">
        <a href="{% url 'filomenas:criar_hospede' %}" class="btn text-orangee btn-buy">Editar</a>
        <a href="{% url 'filomenas:home2' %}" class="btn btn-secondary btn-back">Voltar</a>
        <a href="{% url 'account_logout' %}" class="btn btn-danger">Sair</a>
        </div>

                        <!-- Modal de logout -->
                        <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <img src="{% static 'img/logo.png' %}" alt="" class="rounded-circle" style="width: 80px; height: 70px;">
                                    <h5 class="modal-title" id="exampleModalLabel"><strong>Filomenas</strong>
                                    </h5>
                    
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Fechar"></button>
                                </div>
                                <div class="modal-body">
                                    <p><strong>{{ request.user.username }}</strong>, você tem certeza de que deseja sair?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar
                                    </button>
                                    <button type="button" class="btn a" id="confirmLogout">Sair</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <script>
                        document.getElementById('confirmLogout').addEventListener('click', function () {
                            document.getElementById('logoutForm').submit();
                        });
                    </script>
                    
                    <!-- Formulário de logout -->
                    <form id="logoutForm" method="post" action="{% url 'account_logout' %}"
                        style="display: none;">
                        {% csrf_token %}
                        {% if redirect_field_value %}
                        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                        {% endif %}
                    </form>
                </div>   
    
    </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

filomenas/templates/logado/perfilinfo.html
{% extends 'base_logada.html' %}
{% load static %}

{% block body %}
<img src="{% static 'img/estampa.png' %}" alt="FOTO-DO-TERREIRO" style="width: 100%; filter: blur(1px); height: 40px;" />
<br><br>
{% block header %}
    <h1>{{ hospedes.0.nome }} - Perfil</h1>
{% endblock %}

<style>
    table.profile-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    table.profile-table th, table.profile-table td {
        border: 1px solid #ddd;
        padding: 12px;
        text-align: left;
    }

    table.profile-table th {
        background-color: #E28743;
        color: white;
        font-weight: bold;
    }

    table.profile-table img {
        border-radius: 50%;
        margin-right: 10px;
    }
</style>
<table class="profile-table">
    <thead>
        <tr>
            <th>Foto</th>
            <th>Nome completo</th>
            <th>Profissão</th>
            <th>Email</th>
            <th>Idade</th>
            <th>Telefone</th>
        </tr>
    </thead>
    <tbody>
        {% for hospede in hospedes %}
            <tr>
                <td><img src="{{ hospede.imagem_perfil.url }}" alt="Foto do Perfil" width="50" height="50"></td>
                <td>{{ hospede.nome }}</td>
                <td>{{ hospede.profissao }}</td>
                <td>{{ hospede.email }}</td>
                <td>{{ hospede.idade }}</td>
                <td>{{ hospede.telefone }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

 
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}


    