filomenas/urls.py
from django.urls import path
from . import views

app_name = "filomenas"

urlpatterns = [
    # nao logado
    path('', views.Home.as_view(), name='home'),
    path('filo/', views.filomena_nao.as_view(), name="filomena_nao"),

    # logado
    path('home2/', views.Home2.as_view(), name='home2'),    
    path('perfil/', views.Perfil.as_view(), name="perfil"),
    
    #listar
    path('listar/', views.ListarEstadia.as_view(), name="listar_log"),
    path('listarfilo/', views.ListarEstadiafilo.as_view(), name="listar_filo"),
    path('listarfilomena/', views.Listarfilomena.as_view(), name="listar_filomena"),
    path('listar_nao/', views.ListarEstadianao.as_view(), name="listar_nao"),

    #detalhar
    path('detalhar_log/<int:pk>/', views.Detalharestadialog.as_view(), name="detalhar_log"),
    path('detalhar/<int:pk>/', views.DetalharEstadia.as_view(), name="detalhar"),

    #criar
    path('criar/', views.CriarEstadia.as_view(), name="criar"),
    path('criar_hospede/', views.Criarhospede.as_view(), name="criar_hospede"),
    path('criar_filomena/', views.Criarfilomena.as_view(), name="criar_filomena"),
    path('forms/', views.forms.as_view(), name="forms"),
 
    #apagar
    path('apagar_filomena/<int:pk>/', views.Apagarfilomena.as_view(), name='apagar_filomena'),
    path('apagar_estadia/<int:pk>/', views.ApagarEstadia.as_view(), name='apagar_estadia'),

    #atualizar
    path('atualizar_estadia/<int:pk>/', views.AtualizarEstadia.as_view(), name="atualizar_estadia"),
    path('atualizar_filomena/<int:pk>/', views.Atualizarfilomena.as_view(), name="atualizar_filomena"),

    path('atualizar_hosp/<int:pk>/', views.Atualizarhospede.as_view(), name="atuar_hospede"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path("", include("filomenas.urls", namespace="filomenas")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_logada.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
    <link href="{% static 'css/c.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-eaQlHAqNLTVzjB3T3aP/1uPFpXDdMq9j1BwEO21BvQ+ofF2eXP4j4BPDAz9zFjzB" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
          <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Bootstrap JS Bundle (inclui o Popper.js) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

  <!-- jQuery (necessário para Bootstrap JS) -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Bem-vindos</title>
</head>

{% block nav %}

<body>

    <header id="header">
        <div class="container">

            <div class="flex">

                <a href="#"><img src="{% static 'img/logo.png' %}" width="70" height="60"></a>

                <nav>
                    <ul class="align-items-center">
                        <li><a href="{% url 'filomenas:home2' %}"><strong>Home</strong></a></li>
                        <li><a href="{% url 'filomenas:listar_log' %}"><strong>Pacotes</strong></a></li>
                        <li><a href="{% url 'filomenas:listar_filo' %}"><strong>Filomenas</strong></a></li> 
                        <li><a href="{% url 'filomenas:listar_filomena' %}"><strong>Admin

                            
                        </strong></a></li>
                        <li><a href="{% url 'filomenas:forms' %}"><strong>Formulários</strong></a></li>

                    </ul>
                </nav>

                <div class="dropdown">
                    <div class="btn-contato dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <a href="{% url 'filomenas:perfil' %}">
                            <button>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                    class="bi bi-person-fill" viewBox="0 0 16 16">
                                    <path
                                        d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
                                </svg> Olá, {{ request.user.username }}
                            </button>
                        </a>
                    </div>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li>
                            <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#logoutModal">
                                SAIR
                            </a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'filomenas:perfil' %}">Perfil</a></li>
                    </ul>
                </div>
                
                <style>
                
                    .modal-title {
                        color: #E28743;
                    }
                
                    .a {
                        background-color: #cb6c24;
                        color: white;
                    }
                
                    .a:hover {
                        background-color: #E28743;
                    }
                
                    .rounded-avatar {
                        border-radius: 50%;
                    }
                </style>
                
                <!-- Modal de logout -->
                <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <img src="{% static 'img/logo.png' %}" alt="" class="rounded-circle" style="width: 80px; height: 70px;">
                                <h5 class="modal-title" id="exampleModalLabel"><strong>Filomenas</strong>
                                </h5>
                
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Fechar"></button>
                            </div>
                            <div class="modal-body">
                                <p><strong>{{ request.user.username }}</strong>, você tem certeza de que deseja sair?</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar
                                </button>
                                <button type="button" class="btn a" id="confirmLogout">Sair</button>
                            </div>
                        </div>
                    </div>
                </div>
                
                <script>
                    document.getElementById('confirmLogout').addEventListener('click', function () {
                        document.getElementById('logoutForm').submit();
                    });
                </script>
                
                <!-- Formulário de logout -->
                <form id="logoutForm" method="post" action="{% url 'account_logout' %}"
                    style="display: none;">
                    {% csrf_token %}
                    {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                    {% endif %}
                </form>
            </div>   

    </header>

</body>

{% endblock nav %}

{% block body %}

{% endblock body %}

{% block footer %}

<br><br><br><br><br><br><br><br><br><br>

<footer style="background-color: #E28743; color: white; padding: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-unstyled">
                    <li><a href="#" class="text-decoration-none text-white">Página Inicial</a></li>
                    <li><a href="#" class="text-decoration-none text-white">Sobre a Empresa</a></li>
                    <li><a href="#" class="text-decoration-none text-white">Galeria de Fotos</a></li>
                    <li><a href="#" class="text-decoration-none text-white">Fale Conosco</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <!-- Adicione mais colunas ou conteúdo conforme necessário -->
            </div>
            <div class="col-md-4">
                <p>Redes sociais:</p>
                <p><i class="bi bi-instagram"></i> @Filomenas2019</p>
                <p><i class="bi bi-facebook"></i> Facebook</p>
                <p><i class="bi bi-whatsapp"></i> (84) 90000-0000</p>
            </div>
        </div>
    </div>

    <div class="text-center mt-3">
        <p>&copy; 2023 Filomenas - Todos os direitos reservados.</p>
        <p>Desenvolvido por: <a href="#" class="text-white" title="Maria Rita Paiva">Maria Rita Paiva</a> e <a
                href="#" class="text-white" title="Wesley Kauan">Wesley Kauan</a></p>
    </div>
</footer>

</html>

{% endblock footer %}

templates/base_nao.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/c.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutFLQF4K3qEXvJz1P2GOJg5x9SPDKHQw8I/CI2vX38bfe" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyE12yzl3e4YlrJ6RS5tzgD81I6z5Y2a2H" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-b1Ffhae9kr4LQrN2t4jz+qtH4cB2NpVDb+V2eHNZDAdVgI8PKOnuL57frtGOnQiY" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-i-4SLZ7L+WCGGj2Qfkti1JoYq4K3BLtuAP+txDWoT2uAd5VDZF1VZTcI2iJ4ocKml" crossorigin="anonymous"></script>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Bootstrap JS Bundle (inclui o Popper.js) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

  <!-- jQuery (necessário para Bootstrap JS) -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Bem-vindos</title>
</head>

{% block nav %}
   
<body> 

    <header id="header">
        <div class="container">


            <div class="flex">

            <a href="#"><img src="{% static 'img/logo.png' %}" width="70" height="60"></a>

            <nav style="justify-content: center;">
              <ul>
                  <li><a href="{% url 'filomenas:home' %}"><strong>Home</strong></a></li>
                  <li><a href="{% url 'filomenas:listar_nao' %}"><strong>Pacotes</strong></a></li>
                  <li><a href="{% url 'filomenas:filomena_nao' %}"><strong>Filomenas</strong></a></li>
              </ul>
          </nav>
          

            <div class="btn-contato">

                <a href="{% url 'account_login' %}"><button><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
                  </svg> Entrar</button></a>
                <!-- <a href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                      </svg>
                </a> -->

               
                <!-- <a href="{% url 'account_signup' %}"><button>Cadastre-se</button></a> -->


            </div>

            </div>
        </div>

    </header>


</body>

{% endblock nav %}
    

{% block body %}

{% endblock body %}
    

{% block footer %}
  
<br><br><br><br><br><br><br><br><br><br>


<footer style="background-color: #E28743; color: white; padding: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <ul class="list-unstyled">
                    <li><a href="#" class="text-decoration-none text-white">Página Inicial</a></li>
                    <li><a href="#" class="text-decoration-none text-white">Sobre a Empresa</a></li>
                    <li><a href="#" class="text-decoration-none text-white">Galeria de Fotos</a></li>
                    <li><a href="#" class="text-decoration-none text-white">Fale Conosco</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <!-- Adicione mais colunas ou conteúdo conforme necessário -->
            </div>
            <div class="col-md-4">
                <p>Redes sociais:</p>
                <p><i class="bi bi-instagram"></i> @Filomenas2019</p>
                <p><i class="bi bi-facebook"></i> Facebook</p>
                <p><i class="bi bi-whatsapp"></i> (84) 90000-0000</p>
            </div>
        </div>
    </div>

    <div class="text-center mt-3">
        <p>&copy; 2023 Filomenas - Todos os direitos reservados.</p>
        <p>Desenvolvido por: <a href="#" class="text-white" title="Maria Rita Paiva">Maria Rita Paiva</a> e <a href="#" class="text-white" title="Wesley Kauan">Wesley Kauan</a></p>
    </div>
</footer>

</html>

{% endblock footer %}